name: Code Quality

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-quality-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-quality-
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        pip install bandit safety pylint mypy
    
    - name: Security check with bandit
      run: |
        bandit -r medchem_filter/ -ll -f json -o bandit-report.json || true
        bandit -r medchem_filter/ -ll
      continue-on-error: true
    
    - name: Dependency security check
      run: |
        safety check --json || true
      continue-on-error: true
    
    - name: Static type checking with mypy
      run: |
        mypy medchem_filter/ --ignore-missing-imports --no-strict-optional
      continue-on-error: true
    
    - name: Code analysis with pylint
      run: |
        pylint medchem_filter/ --fail-under=8.0 --rcfile=.pylintrc || true
      continue-on-error: true
    
    - name: Upload security report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.json
